version: '3.0'

services:
  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - 27017:27017
  # mongo-express:
  #     image: mongo-express
  #     restart: always
  #     ports:
  #       - 8081:8081
  #     environment:
  #       ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #       ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     depends_on:
  #       - mongo
  apigateway:
    image: apigateway
    build:
      context: ./APIGateway
    environment:
      ASPNETCORE_URLS: http://*:80
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "80:80"
    env_file:
      ./nexus.env

  summoner.api:
    image: nexus-summoner.api
    build:
      context: ./SummonerAPI
    environment:
      ASPNETCORE_URLS: http://*:80
      ASPNETCORE_ENVIRONMENT: Development
    env_file:
      ./nexus.env